# Generated by Django 5.2.7 on 2025-11-20 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_remove_course_description_batch_filled_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='filled_seats',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='courses_app.course'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='total_seat',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
