import type { Metadata } from "next";
import { Geist, Geist_Mono, Hind_Siliguri } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const hindSiliguri = Hind_Siliguri({
  variable: "--font-hind-siliguri",
  subsets: ["bengali", "latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Sunny's Math World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeInit = `
    (function(){
      try {
        var root = document.documentElement;
        var path = window.location.pathname || '';
        var inDashboard = path.startsWith('/dashboard');
        if (!inDashboard) {
          root.classList.remove('dark');
          root.setAttribute('data-theme', 'emerald');
          return;
        }
        var m = localStorage.getItem('theme-mode');
        var p = localStorage.getItem('theme-palette') || 'emerald';
        var mode = (m === 'light' || m === 'dark') ? m : 'light';
        root.classList.toggle('dark', mode === 'dark');
        root.setAttribute('data-theme', p);
      } catch (e) {}
    })();
  `;

  const scrollbarInit = `
    (function(){
      try {
        var css = 'body[data-scroll-locked]{overflow-y:visible !important;padding-right:0 !important;margin-right:0 !important;padding-left:0 !important;margin-left:0 !important;}';
        var styleId = 'scrollbar-stable-style';
        var ensureStyle = function(){
          var head = document.head;
          if (!head) return;
          var style = document.getElementById(styleId);
          if (!style) {
            style = document.createElement('style');
            style.id = styleId;
            style.appendChild(document.createTextNode(css));
          }
          head.appendChild(style);
        };
        var observeBody = function(body){
          if (!body) return;
          new MutationObserver(function(mutations){
            for (var i = 0; i < mutations.length; i++) {
              if (mutations[i].type === 'attributes') {
                ensureStyle();
                break;
              }
            }
          }).observe(body, { attributes: true, attributeFilter: ['data-scroll-locked'] });
        };
        if (document.readyState === 'loading') {
          document.addEventListener('DOMContentLoaded', function(){
            ensureStyle();
            observeBody(document.body);
          });
        } else {
          ensureStyle();
          observeBody(document.body);
        }
      } catch (e) {}
    })();
  `;
  return (
    <html lang="en" suppressHydrationWarning data-theme="emerald" className={`${hindSiliguri.variable}`}>
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}>
        <script dangerouslySetInnerHTML={{ __html: themeInit }} />
        <script dangerouslySetInnerHTML={{ __html: scrollbarInit }} />
        {children}
      </body>
    </html>
  );
}
