import type { Metadata } from "next";
import { Geist, Geist_Mono, Hind_Siliguri } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/auth/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const hindSiliguri = Hind_Siliguri({
  variable: "--font-hind-siliguri",
  subsets: ["bengali", "latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Sunny's Math World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeInit = `
    (function(){
      try {
        var root = document.documentElement;
        var path = window.location.pathname || '';
        var inDashboard = path.startsWith('/admin');
        if (!inDashboard) {
          root.classList.remove('dark');
          root.setAttribute('data-theme', 'emerald');
          return;
        }
        var m = localStorage.getItem('theme-mode');
        var p = localStorage.getItem('theme-palette') || 'emerald';
        var mode = (m === 'light' || m === 'dark') ? m : 'light';
        root.classList.toggle('dark', mode === 'dark');
        root.setAttribute('data-theme', p);
      } catch (e) {}
    })();
  `;
  return (
    <html lang="en" suppressHydrationWarning data-theme="emerald" className={`${hindSiliguri.variable}`}>
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}>
        <script dangerouslySetInnerHTML={{ __html: themeInit }} />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
