# Generated by Django 5.2.1 on 2025-10-15 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('name_en', models.CharField(max_length=150)),
                ('name_bn', models.CharField(blank=True, max_length=150, null=True)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name_en', models.CharField(max_length=100)),
                ('student_last_name_en', models.CharField(max_length=100)),
                ('student_nick_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('student_first_name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('student_last_name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('student_nick_name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('current_class', models.CharField(max_length=50)),
                ('prev_result', models.CharField(blank=True, max_length=120, null=True)),
                ('student_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('home_location', models.TextField(blank=True, null=True)),
                ('picture_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_submitted', models.BooleanField(default=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='courses_app.batch')),
            ],
        ),
    ]
