# Generated by Django 5.2.7 on 2025-11-12 01:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_initial'),
        ('courses_app', '0002_remove_course_description_batch_filled_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='student_first_name_bn',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='student_first_name_en',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='student_last_name_bn',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='student_last_name_en',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='student_nick_name_bn',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='student_nick_name_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='HELD', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='admissions.admissionapplication')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='courses_app.batch')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'status', 'expires_at'], name='admissions__batch_i_6a5fcd_idx')],
            },
        ),
    ]
