# Backend/admissions/migrations/0004_rename_current_class_admissionapplication_class_level_and_more.py
# Generated by Django 5.2.7 on 2025-11-16 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_admissionapplication_is_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionapplication',
            old_name='current_class',
            new_name='class_level',
        ),
        migrations.RenameField(
            model_name='admissionapplication',
            old_name='prev_result',
            new_name='home_district',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='student_first_name_en',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='student_last_name_en',
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='batch_timing_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='group',
            field=models.CharField(choices=[('science', 'Science'), ('humanities', 'Humanities'), ('business', 'Business Studies'), ('other', 'Other')], default='science', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='has_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='hear_about_us',
            field=models.CharField(blank=True, choices=[('social-media', 'Social media'), ('friend', 'Friend'), ('prev-student', 'Previous student'), ('poster-banner', 'Poster / Banner'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='jsc_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='jsc_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='prev_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='ssc_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='ssc_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='student_full_name_en',
            field=models.CharField(default='default name', max_length=150),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardian',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
