# Generated by Django 5.2.7 on 2025-11-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_rename_current_class_admissionapplication_class_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionapplication',
            old_name='class_level',
            new_name='current_class',
        ),
        migrations.RenameField(
            model_name='admissionapplication',
            old_name='home_district',
            new_name='prev_result',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='batch_timing_code',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='father_occupation',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='father_phone',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='group',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='guardian_contact',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='guardian_relation',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='has_photo',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='hear_about_us',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='jsc_grade',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='jsc_school',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='mother_occupation',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='mother_phone',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='prev_student',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='ssc_grade',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='ssc_school',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='student_full_name_en',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='student_first_name_en',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='student_last_name_en',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='role',
            field=models.CharField(max_length=10),
        ),
    ]
