# Generated by Django 5.2.7 on 2025-11-20 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_rename_class_level_admissionapplication_current_class_and_more'),
        ('courses_app', '0003_remove_batch_filled_seats_course_description_and_more'),
        ('users', '0002_remove_userprofile_school_userprofile_school_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionapplication',
            name='school',
        ),
        migrations.RenameField(
            model_name='admissionapplication',
            old_name='prev_result',
            new_name='home_district',
        ),
        migrations.RenameField(
            model_name='admissionapplication',
            old_name='student_first_name_bn',
            new_name='jsc_result',
        ),
        migrations.RenameField(
            model_name='admissionapplication',
            old_name='is_approved',
            new_name='prev_student',
        ),
        migrations.RenameField(
            model_name='admissionapplication',
            old_name='student_last_name_bn',
            new_name='ssc_result',
        ),
        migrations.RenameField(
            model_name='admissionapplication',
            old_name='student_first_name_en',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='admissionapplication',
            old_name='student_nick_name_bn',
            new_name='student_nick_name',
        ),
        migrations.RenameField(
            model_name='guardian',
            old_name='name_en',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='is_submitted',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='student_last_name_en',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='student_nick_name_en',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='name_bn',
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='hear_about_us',
            field=models.CharField(blank=True, choices=[('social-media', 'Social media'), ('friend-family', 'Friend / family'), ('prev-student', 'Previous student'), ('banner', 'Banner / poster'), ('other', 'Other')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='jsc_school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='ssc_school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (awaiting payment)'), ('PAID', 'Paid / Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guardian',
            name='is_primary_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='role',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='seathold',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'HELD')), fields=('application',), name='unique_active_hold_per_application'),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
