# Generated by Django 5.2.1 on 2025-10-15 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default='ADMISSION_FEE', max_length=32)),
                ('method', models.CharField(choices=[('SSLC', 'SSLCommerz'), ('MANL', 'Manual')], default='SSLC', max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=8)),
                ('status', models.CharField(choices=[('INIT', 'Initiated'), ('SUCC', 'Success'), ('FAIL', 'Failed')], default='INIT', max_length=4)),
                ('gateway_trx_id', models.CharField(blank=True, max_length=128)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admissions.admissionapplication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
