# Backend/payments/migrations/0001_initial.py
# Generated by Django 5.2.7 on 2025-11-08 04:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tran_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=8)),
                ('gateway', models.CharField(default='SSLCOMMERZ', max_length=32)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('REDIRECTED', 'Gateway Redirected'), ('SUCCESS_REDIRECT', 'Success (browser)'), ('FAIL_REDIRECT', 'Fail (browser)'), ('CANCEL_REDIRECT', 'Cancel (browser)'), ('VALIDATED', 'Validated'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='INITIATED', max_length=32)),
                ('application_id', models.IntegerField(blank=True, null=True)),
                ('create_payload', models.JSONField(blank=True, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('validation_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
