# Generated by Django 5.2.7 on 2025-11-20 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_remove_admissionapplication_school_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.AddField(
            model_name='payment',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='admissions.admissionapplication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_trx_id',
            field=models.CharField(blank=True, help_text='Transaction ID returned by SSLCommerz (if different from tran_id).', max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('SSLC', 'SSLCommerz'), ('MANL', 'Manual')], default='SSLC', max_length=4),
        ),
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(default='ADMISSION_FEE', max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_risk_level',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_risk_title',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_val_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('REDIRECTED', 'Gateway redirected'), ('SUCCESS_REDIRECT', 'Success (browser)'), ('FAIL_REDIRECT', 'Fail (browser)'), ('CANCEL_REDIRECT', 'Cancel (browser)'), ('VALIDATED', 'Validated (via val_id/IPN)'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='INITIATED', max_length=32),
        ),
    ]
